FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
      libpq-dev gcc \
      && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /usr/src/app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY ./app ./app

# Copy any other necessary files from the root directory
COPY schema.sql .
COPY prometheus.yml .

# Expose application port (if necessary)
EXPOSE 5000

# Run the application
CMD ["python", "app/app.py"]